---
# Setting specific variables for monitoring services
- name: Set service variables
  set_fact:
    service_name: "monitoring"

# Include common service setup tasks
- name: Include service setup tasks
  include_role:
    name: service_setup

# monitoring role tasks

- name: Create required directories
  file:
    path: "/root/monitoring"
    state: directory
    mode: '0755'
