#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copy tint2 config if not exists
if [[ ! -f /config/.config/tint2/tint2rc ]]; then
    mkdir -p /config/.config/tint2
    cp /defaults/tint2rc /config/.config/tint2/tint2rc
fi

# Copy openbox config if not exists
if [[ ! -f /config/.config/openbox/menu.xml ]]; then
    mkdir -p /config/.config/openbox
    cp /defaults/menu.xml /config/.config/openbox/menu.xml
fi

if [[ ! -f /config/.config/openbox/autostart ]]; then
    mkdir -p /config/.config/openbox
    cp /defaults/autostart /config/.config/openbox/autostart
fi

# permissions
lsiown -R abc:abc \
    /config
lsiown -R abc:abc \
    /opt/obsidian
