networks:
  proxy-net:
    driver: bridge

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --protocol http2 run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN:?Cloudflare tunnel token must be defined}
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Istanbul}
    
    networks:
      - proxy-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  cadvisor-proxy:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor-proxy
    privileged: true
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - proxy-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower-proxy:
    image: containrrr/watchtower:latest
    container_name: watchtower-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 8,14,20,2 * * *
      - PUID=1000
      - PGID=1000
      - UMASK=002
    restart: unless-stopped
    networks:
      - proxy-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
