

networks:
  proxy-net:
    driver: bridge

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --protocol http2 run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN:?Cloudflare tunnel token must be defined}
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Istanbul}
    
    networks:
      - proxy-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cadvisor:
    extends:
      service: common-cadvisor
    container_name: cadvisor-proxy
    networks:
      - proxy-net

  promtail:
    extends:
      service: common-promtail
    container_name: promtail-proxy
    networks:
      - proxy-net

  watchtower:
    extends:
      service: common-watchtower
    container_name: watchtower-proxy
    command: ["--schedule", "0 0 8,14,20,2 * * *"]
    networks:
      - proxy-net