# bookmarks.yaml

- Project:
    - GitHub:
        icon: fab fa-github
        href: "https://github.com/Yakrel/proxmox-homelab-automation"
        description: "Proxmox Homelab Automation Repository"