title: My Homelab Dashboard
background:
  image: https://images.unsplash.com/photo-1604147706283-d7119b5b822c
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 80

layout:
  - Media Services:
      icon: fas fa-film
      items:
        - Sonarr
        - Radarr
        - Bazarr
        - Jellyfin
        - Jellyseerr
        - qBittorrent
        - Prowlarr

  - Download Tools:
      icon: fas fa-download
      items:
        - JDownloader2
        - MeTube
        - Palmr

  - Web Tools:
      icon: fas fa-globe
      items:
        - Homepage
        - Firefox

  - Monitoring Tools:
      icon: fas fa-chart-line
      items:
        - Grafana
        - Prometheus

  - Bookmarks:
      icon: fas fa-bookmark
      items:
        - Project:
            items:
              - GitHub