services:
  desktop-workspace:
    image: yakrel93/desktop-workspace:latest
    pull_policy: always
    container_name: desktop-workspace
    hostname: desktop-workspace
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - TITLE=Desktop Workspace
      - CUSTOM_USER=${CUSTOM_USER:?User must be defined}
      - PASSWORD=${PASSWORD:?Password must be defined}
    volumes:
      - /datapool/config/desktop:/config:rw
      - /datapool:/datapool:rw
    ports:
      - "5800:3000"  # HTTPS web interface
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
