---
# Default values for Docker common role

# Docker Compose configuration
docker_compose_project_src: /root
docker_compose_file: docker-compose.yml
docker_compose_env_file: .env
docker_compose_state: present

# Docker service configuration
docker_service_state: started
docker_service_enabled: true
