#!/bin/bash
# Proxmox Network Bonding Setup Script
# Configures network bonding for maximum redundancy and 1Gbps optimization
# Simplified version focusing on essential functionality

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration variables
BOND_NAME="bond0"
BRIDGE_NAME="vmbr0"
IP_ADDRESS=""
GATEWAY=""
NETWORK_MASK="24"

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}================================${NC}"
    echo -e "${BLUE} Proxmox Network Bonding Setup${NC}"
    echo -e "${BLUE}================================${NC}"
}

# Function to detect network interfaces
detect_interfaces() {
    print_status "Detecting ethernet interfaces..."
    
    # Get all ethernet interfaces (excluding lo, docker, etc.)
    INTERFACES=($(ip link show | grep -E '^[0-9]+: enp|^[0-9]+: eth' | cut -d: -f2 | tr -d ' '))
    
    if [ ${#INTERFACES[@]} -eq 0 ]; then
        print_error "No ethernet interfaces found!"
        exit 1
    fi
    
    if [ ${#INTERFACES[@]} -eq 1 ]; then
        print_warning "Only one interface found. Bonding requires multiple interfaces."
        echo "Found: ${INTERFACES[*]}"
        read -p "Continue anyway? (y/N): " confirm
        if [[ ! $confirm =~ ^[Yy]$ ]]; then
            exit 0
        fi
    fi
    
    print_status "Found ${#INTERFACES[@]} interfaces: ${INTERFACES[*]}"
}

# Function to get network configuration
get_network_config() {
    print_status "Network configuration required:"
    echo
    
    # Auto-detect current IP and gateway
    CURRENT_IP=$(ip route get 1 2>/dev/null | grep -Po '(?<=src )[0-9.]+' | head -1)
    CURRENT_GW=$(ip route | grep default | grep -Po '(?<=via )[0-9.]+' | head -1)
    
    # Get IP address
    if [ ! -z "$CURRENT_IP" ]; then
        read -p "IP Address [$CURRENT_IP]: " IP_ADDRESS
        IP_ADDRESS=${IP_ADDRESS:-$CURRENT_IP}
    else
        read -p "IP Address: " IP_ADDRESS
        while [[ ! $IP_ADDRESS =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; do
            print_error "Invalid IP address format"
            read -p "IP Address: " IP_ADDRESS
        done
    fi
    
    # Get gateway
    if [ ! -z "$CURRENT_GW" ]; then
        read -p "Gateway [$CURRENT_GW]: " GATEWAY
        GATEWAY=${GATEWAY:-$CURRENT_GW}
    else
        read -p "Gateway: " GATEWAY
        while [[ ! $GATEWAY =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; do
            print_error "Invalid gateway format"
            read -p "Gateway: " GATEWAY
        done
    fi
    
    # Get network mask
    read -p "Network Mask [24]: " NETWORK_MASK
    NETWORK_MASK=${NETWORK_MASK:-24}
    
    echo
    print_status "Configuration summary:"
    echo "  IP: $IP_ADDRESS/$NETWORK_MASK"
    echo "  Gateway: $GATEWAY"
    echo "  Bond: ${INTERFACES[*]} → $BOND_NAME → $BRIDGE_NAME"
    echo
}

# Function to create backup
create_backup() {
    print_status "Creating configuration backup..."
    
    BACKUP_DIR="/root/network-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    # Backup essential files
    [ -f /etc/network/interfaces ] && cp /etc/network/interfaces "$BACKUP_DIR/"
    [ -f /etc/rc.local ] && cp /etc/rc.local "$BACKUP_DIR/"
    [ -f /etc/modules ] && cp /etc/modules "$BACKUP_DIR/"
    
    print_status "Backup saved to: $BACKUP_DIR"
}

# Function to setup bonding module
setup_bonding_module() {
    print_status "Configuring bonding module..."
    
    # Load bonding module
    modprobe bonding 2>/dev/null || true
    
    # Add to modules for persistent loading
    if ! grep -q "^bonding" /etc/modules 2>/dev/null; then
        echo 'bonding' >> /etc/modules
    fi
}

# Function to create network interfaces configuration
create_network_config() {
    print_status "Creating network configuration..."
    
    cat > /etc/network/interfaces << EOF
# Network Interfaces Configuration
# Auto-generated by Proxmox Bonding Setup Script
# Generated: $(date)

auto lo
iface lo inet loopback

# Network Bond - Active-Backup Mode
auto $BOND_NAME
iface $BOND_NAME inet manual
    bond-slaves ${INTERFACES[*]}
    bond-mode active-backup
    bond-miimon 100
    bond-downdelay 200
    bond-updelay 200
    bond-primary ${INTERFACES[0]}

EOF

    # Add individual interface configurations
    for interface in "${INTERFACES[@]}"; do
        cat >> /etc/network/interfaces << EOF
# Interface $interface - Bond slave
auto $interface
iface $interface inet manual
    bond-master $BOND_NAME

EOF
    done

    # Add bridge configuration
    cat >> /etc/network/interfaces << EOF
# Bridge for VMs/CTs
auto $BRIDGE_NAME
iface $BRIDGE_NAME inet static
    address $IP_ADDRESS/$NETWORK_MASK
    gateway $GATEWAY
    bridge-ports $BOND_NAME
    bridge-stp off
    bridge-fd 0

source /etc/network/interfaces.d/*
EOF

}

# Function to create 1Gbps optimization
create_speed_optimization() {
    print_status "Creating 1Gbps speed optimization..."
    
    cat > /etc/rc.local << 'EOF'
#!/bin/bash
# Network Speed Optimization
# Auto-generated by Proxmox Bonding Setup Script

# Wait for interfaces to be ready
sleep 10

# Force 1Gbps on all ethernet interfaces
EOF

    for interface in "${INTERFACES[@]}"; do
        cat >> /etc/rc.local << EOF
ethtool -s $interface autoneg off speed 1000 duplex full 2>/dev/null || true
sleep 1
ethtool -s $interface autoneg on 2>/dev/null || true
EOF
    done

    cat >> /etc/rc.local << 'EOF'

exit 0
EOF

    chmod +x /etc/rc.local
    systemctl enable rc-local 2>/dev/null || true
}

# Function to apply configuration
apply_configuration() {
    print_warning "Applying network configuration..."
    print_warning "Network connectivity will be briefly interrupted!"
    
    read -p "Press Enter to continue or Ctrl+C to abort..."
    
    # Restart networking
    systemctl restart networking
    
    # Wait for interfaces to stabilize
    sleep 5
    
}

# Function to verify configuration
verify_configuration() {
    print_status "Verifying configuration..."
    
    # Test connectivity
    if ping -c 2 -W 3 "$GATEWAY" >/dev/null 2>&1; then
        print_status "Network connectivity verified"
    else
        print_error "Gateway connectivity failed"
        return 1
    fi
}

# Function to show completion message
show_completion() {
    echo
    print_status "Network bonding setup completed successfully!"
    print_status "Cable redundancy enabled - you can plug into any ethernet port"
    echo
}

# Main function
main() {
    print_header
    
    # Root check
    if [ "$EUID" -ne 0 ]; then
        print_error "This script must be run as root"
        exit 1
    fi
    
    # Detect interfaces
    detect_interfaces
    
    # Get configuration
    get_network_config
    
    # Final confirmation
    echo -e "${YELLOW}⚠️  WARNING: This will modify your network configuration!${NC}"
    echo "Current active connections may be interrupted."
    echo
    read -p "Continue with bonding setup? (y/N): " confirm
    if [[ ! $confirm =~ ^[Yy]$ ]]; then
        print_status "Setup cancelled"
        exit 0
    fi
    
    # Execute setup
    create_backup
    setup_bonding_module
    create_network_config
    create_speed_optimization
    apply_configuration
    
    # Verify and show results
    if verify_configuration; then
        show_completion
    else
        print_error "Configuration verification failed!"
        echo "Check network settings and consider restoring from backup."
        exit 1
    fi
}

# Handle interruption
trap 'echo; print_error "Setup interrupted!"; exit 1' INT TERM

# Execute main function
main "$@"