

networks:
  webtools-net:
    driver: bridge

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
       - /datapool/config/homepage:/app/config:rw
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /datapool:/datapool:ro # Added for datapool access
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=192.168.1.103:3000,192.168.1.103,localhost,0.0.0.0
      - HOMEPAGE_VAR_SONARR_API_KEY=${HOMEPAGE_VAR_SONARR_API_KEY}
      - HOMEPAGE_VAR_RADARR_API_KEY=${HOMEPAGE_VAR_RADARR_API_KEY}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${HOMEPAGE_VAR_PROWLARR_API_KEY}
      - HOMEPAGE_VAR_BAZARR_API_KEY=${HOMEPAGE_VAR_BAZARR_API_KEY}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${HOMEPAGE_VAR_JELLYFIN_API_KEY}
      - HOMEPAGE_VAR_JELLYSEERR_API_KEY=${HOMEPAGE_VAR_JELLYSEERR_API_KEY}
      - HOMEPAGE_VAR_QB_USERNAME=${HOMEPAGE_VAR_QB_USERNAME}
      - HOMEPAGE_VAR_QB_PASSWORD=${HOMEPAGE_VAR_QB_PASSWORD}
      - HOMEPAGE_VAR_GRAFANA_USERNAME=${HOMEPAGE_VAR_GRAFANA_USERNAME}
      - HOMEPAGE_VAR_GRAFANA_PASSWORD=${HOMEPAGE_VAR_GRAFANA_PASSWORD}
    networks:
      - webtools-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    restart: unless-stopped
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - /datapool/config/firefox:/config:rw
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - VNC_PASSWORD=${FIREFOX_VNC_PASSWORD:?Firefox VNC password must be defined}
      - PUID=1000
      - PGID=1000
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    networks:
      - webtools-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cadvisor:
    extends:
      service: common-cadvisor
    container_name: cadvisor-webtools
    networks:
      - webtools-net

  promtail:
    extends:
      service: common-promtail
    container_name: promtail-webtools
    networks:
      - webtools-net

  watchtower:
    extends:
      service: common-watchtower
    container_name: watchtower-webtools
    command: ["--schedule", "0 0 8,14,20,2 * * *"]
    networks:
      - webtools-net