input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] =~ /^(sonarr|radarr|bazarr|jellyfin|jellyseerr|qbittorrent|prowlarr|flaresolverr)$/ {
    mutate {
      add_field => { "application" => "%{[container][name]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{application}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
