#!/bin/bash

# Install and configure Tailscale subnet routing on the Proxmox host.
set -euo pipefail

WORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"

source "$WORK_DIR/scripts/helper-functions.sh"

require_root

# Check if Tailscale is already installed and authenticated
tailscale_logged_in=0
if command -v tailscale &>/dev/null && tailscale status &>/dev/null; then
    tailscale_logged_in=1
fi

if [[ "$tailscale_logged_in" -eq 0 && -z "${TAILSCALE_AUTH_KEY:-}" ]]; then
    print_error "Tailscale is not authenticated and TAILSCALE_AUTH_KEY is not set in the environment"
    exit 1
fi

if ! command -v tailscale &>/dev/null; then
    print_info "Installing Tailscale from its signed Debian repository"
    . /etc/os-release
    debian_codename=${VERSION_CODENAME:-}
    if [[ -z "$debian_codename" ]]; then
        print_error "Could not determine Debian VERSION_CODENAME"
        exit 1
    fi

    install -d -m 0755 /usr/share/keyrings
    curl -fsSL \
        "https://pkgs.tailscale.com/stable/debian/${debian_codename}.noarmor.gpg" \
        -o /usr/share/keyrings/tailscale-archive-keyring.gpg
    curl -fsSL \
        "https://pkgs.tailscale.com/stable/debian/${debian_codename}.tailscale-keyring.list" \
        -o /etc/apt/sources.list.d/tailscale.list
    apt-get update -qq
    apt-get install -y -qq tailscale
else
    print_info "Tailscale is already installed on the Proxmox host"
fi

print_info "Enabling IPv4 forwarding"
cat > /etc/sysctl.d/99-tailscale-subnet-router.conf << 'EOF'
net.ipv4.ip_forward = 1
EOF
sysctl -p /etc/sysctl.d/99-tailscale-subnet-router.conf

ensure_packages ethtool

print_info "Configuring persistent UDP GRO/GSO optimization systemd service"

# Create script directory if missing
mkdir -p /usr/local/bin

# Write dynamic optimization script
cat > /usr/local/bin/tailscale-udp-gro.sh << 'EOF'
#!/bin/bash
# Automatically generated by Proxmox Homelab Automation

GW_IF=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
if [[ -n "$GW_IF" ]]; then
    OPT_IFS=("$GW_IF")
    if [[ -d "/sys/class/net/$GW_IF/brif" ]]; then
        for member in $(ls "/sys/class/net/$GW_IF/brif/"); do
            OPT_IFS+=("$member")
            if [[ -d "/sys/class/net/$member/bonding" ]]; then
                for slave in $(cat "/sys/class/net/$member/bonding/slaves"); do
                    OPT_IFS+=("$slave")
                done
            fi
        done
    fi

    UNIQUE_IFS=($(echo "${OPT_IFS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
    for iface in "${UNIQUE_IFS[@]}"; do
        if [[ -d "/sys/class/net/$iface" ]]; then
            echo "Applying UDP GRO optimization to $iface"
            if ! ethtool -K "$iface" rx-udp-gro-forwarding on rx-gro-list off; then
                echo "Interface $iface does not support the requested UDP GRO settings" >&2
            fi
        fi
    done
fi

# TCP MSS Clamping for Tailscale tunnel only (not global FORWARD)
# Prevents packet fragmentation issues when routing traffic through Tailscale
# Kept for restrictive hotspots and networks where a lower path MTU can stall VPN traffic
# Applied only to tailscale0 to avoid affecting local LXC/Docker traffic
if ip link show tailscale0 &>/dev/null; then
    iptables -t mangle -C FORWARD -i tailscale0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
    iptables -t mangle -A FORWARD -i tailscale0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
    iptables -t mangle -C FORWARD -o tailscale0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
    iptables -t mangle -A FORWARD -o tailscale0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
fi
EOF

chmod +x /usr/local/bin/tailscale-udp-gro.sh

# Write systemd service unit
cat > /etc/systemd/system/tailscale-udp-gro.service << 'EOF'
[Unit]
Description=Tailscale UDP GRO Optimization
Wants=network-online.target
After=network-online.target tailscaled.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/tailscale-udp-gro.sh
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
EOF

# Enable the service; run it after Tailscale creates tailscale0 below
systemctl daemon-reload
systemctl enable -q tailscale-udp-gro.service

print_info "Configuring Tailscale subnet route"
if [[ "$tailscale_logged_in" -eq 1 ]]; then
    print_info "Tailscale is already authenticated. Updating subnet routes..."
    tailscale up \
        --advertise-routes=192.168.1.0/24 \
        --accept-dns=false
else
    print_info "Authenticating Tailscale using provided auth key..."
    tailscale up \
        --auth-key="$TAILSCALE_AUTH_KEY" \
        --advertise-routes=192.168.1.0/24 \
        --accept-dns=false
fi

systemctl restart tailscale-udp-gro.service

print_success "Tailscale host subnet router configured"
print_info "Approve the 192.168.1.0/24 route in the Tailscale admin console if it is not pre-approved"
