name: Build and Push Desktop Workspace Image

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-images/desktop-workspace/**'
      - '.github/workflows/build-desktop-workspace.yml'
  schedule:
    # Run every Sunday at 2 AM to rebuild with latest base image and apps
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yakrel93/desktop-workspace
          tags: |
            type=raw,value=latest
            type=sha,prefix={{date 'YYYYMMDD'}}-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-images/desktop-workspace
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=yakrel93/desktop-workspace:latest
          cache-to: type=inline

      - name: Clean up old tags
        run: |
          # Get all tags except 'latest'
          TAGS=$(curl -s -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/desktop-workspace/tags/?page_size=100" \
            | jq -r '.results[] | select(.name != "latest") | .name' | sort -r)

          # Keep only the 5 most recent dated tags, delete the rest
          echo "$TAGS" | tail -n +6 | while read -r tag; do
            echo "Deleting tag: $tag"
            curl -s -X DELETE \
              -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/desktop-workspace/tags/$tag/"
          done
