---
# Setting specific variables for media services
- name: Set service variables
  set_fact:
    service_name: "media"

# Include common service setup tasks
- name: Include service setup tasks
  include_role:
    name: service_setup
