---
# Handlers for the backup role

- name: Restart proxmox-backup
  ansible.builtin.service:
    name: proxmox-backup
    state: restarted
  delegate_to: "{{ hostname }}"

- name: Reload proxmox-backup
  ansible.builtin.service:
    name: proxmox-backup
    state: reloaded
  delegate_to: "{{ hostname }}"

- name: Restart proxmox-backup-proxy
  ansible.builtin.service:
    name: proxmox-backup-proxy
    state: restarted
  delegate_to: "{{ hostname }}"
